# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bffe8f1e67a53b13480a07c22eac4f0f"
name = "shop-chat-agent"
application_url = "https://orange-conventions-current-avatar.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://orange-conventions-current-avatar.trycloudflare.com/api/auth" ]

[customer_authentication]
redirect_uris = [
  "https://orange-conventions-current-avatar.trycloudflare.com/callback"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
