export const questions = [
  {
    question: "What is the return policy?",
    answer: "We offer a 30-day return policy for all products.",
    id: "1",
    answered: false,
    date: "2025-01-01",
  },
  {
    question: "What is the shipping policy?",
    answer: "We offer a 30-day shipping policy for all products.",
    id: "2",
    answered: true,
    date: "2025-01-01",
  },
  {
    question: "What is the warranty policy?",
    answer: "We offer a 30-day warranty policy for all products.",
    id: "3",
    answered: false,
    date: "2025-01-01",
  },
  {
    question: "What is the refund policy?",
    answer: "We offer a 30-day refund policy for all products.",
    id: "4",
    answered: false,
    date: "2025-01-01",
  },
  {
    question: "What is the exchange policy?",
    answer: "We offer a 30-day exchange policy for all products.",
    id: "5",
    answered: false,
    date: "2025-01-01",
  },
  {
    question: "What is the cancellation policy?",
    answer: "We offer a 30-day cancellation policy for all products.",
    id: "6",
    answered: true,
    date: "2025-01-01",
  },
  {
    question: "What is the privacy policy?",
    answer: "We offer a 30-day privacy policy for all products.",
    id: "7",
    answered: true,
    date: "2025-01-01",
  },
  {
    question: "What is the terms of service?",
    answer: "We offer a 30-day terms of service for all products.",
    id: "8",
    answered: true,
    date: "2025-01-01",
  },
];
